#!/bin/bash
# Copyright (c) 2019 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Original source
# https://github.com/ansible/python-builder-image/blob/main/scripts/install-from-bindep

# Make a list of bindep dependencies and install them.
set -ex

# NOTE(pabelanger): Allow users to force either  a package manager.
PKGMGR="${PKGMGR:-}"
PKGMGR_OPTS="${PKGMGR_OPTS:-}"

if [ -z "$PKGMGR" ]; then
    # Expect apt-get to be installed.
    PKGMGR=/usr/bin/apt-get
fi

# shellcheck disable=SC2086
$PKGMGR update --yes --quiet $PKGMGR_OPTS

if [ -f bindep.txt ] ; then
    PACKAGES=$(bindep --list_all newline | sort)
    if [ -n "$PACKAGES" ]; then
        # shellcheck disable=SC2086
        DEBIAN_FRONTEND=noninteractive $PKGMGR install --yes --quiet --no-install-recommends $PKGMGR_OPTS $PACKAGES
    fi
fi

# clean up after ourselves
$PKGMGR clean
rm -rf /var/lib/apt/lists/*
